language: rust
rust:
  - stable
  - nightly
cache: cargo

env:
  - COMMAND=""
  - COMMAND=size_check

matrix:
  allow_failures:
    - rust: nightly
    - env: COMMAND=size_check
  fast_finish: true

install:
  - rustup target add thumbv7em-none-eabihf

script: tools/check.py $COMMAND
